### ISSUE TITLE
fetchJSON - using "text()" method on response blocks body stream

### ISSUE THREAD

**Issue by hornetDC** [vlki/refresh-fetch#12]
Hi. I wanted my `fetchWithToken` function to return `Promise<Response>` like regular fetch. 
When working with fetch, I usually return response as `response.json()`, but request returned by `configureRefreshFetch` gave me an error: `Failed to execute 'json' on 'Response': body stream is locked`.
https://stackoverflow.com/q/53511974

This can be solved by cloning response in `getResponseBody` func before using text().

**Comment by vlki** [comment]
Hey, yeah, good point. Changed and released as v0.7.0
