### ISSUE TITLE
Can this be used with OAuth?

### ISSUE THREAD

**Issue by ptmkenny** [vlki/refresh-fetch#15]
Is this project suitable for use with OAuth, when there are two tokens, an access token and a refresh token?  Based on the README, I thought I might be able to use it, but I ran into some trouble.

I used a customized version of the example code, and when I got to the part where I had to save the cookie, I did this:

```
    .then(response => {
      saveToken(response.body)
    })
```

For Drupal 8 (my CMS), `response.body` looks like this:

```
access_token: "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6IjllMTM5NjI5NDY3ZTA1NWU2YjY"
expires_in: 300
refresh_token: "def5020061b40b67759f0cc4079977c9200d867b9f25f82497594344d8a8cb7c5c3ddcebe55fba"
token_type: "Bearer"
```

I was able to log in, but all my requests to the Drupal 8 JSON:API are now failing with a 403 permissions error.

Of course, I will solve the Drupal error by myself, but what I would like to ask here is, is OAuth a common use case for refresh-fetch?

If so, how do I need to structure my cookie?  I'm new to React / OAuth so this may be something very obvious, but I'd appreciate any help you could provide.

**Comment by vlki** [comment]
Hey @ptmkenny, yeah, there should be no problem with using refresh-fetch for OAuth. When logging in, you should save separately refresh token and access token and then when you need to refresh the access token, you just use the refresh token to do it.

**Comment by ptmkenny** [comment]
Ok thanks, I'll try to do that.  I was saving them both in the same cookie, so I guess that was the problem.
